[package]
name = "rust_library_static"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "minus_static1"
crate-type = ["staticlib"]

[dependencies]

[profile.dev]
strip = true