[package]
name = "rust_library_dyn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "minus_dyn"
crate-type = ["cdylib"]

[dependencies]
