[package]
name = "socket_examples"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.2.0"
anyhow = "1.0.44"
tokio = { version = "1.11.0", features = ["full"] }
