[package]
name = "poem_examples"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = "0.8.0"
tokio = { version = "1.12.0", features = ["full"] }
tracing-subscriber = "0.2.24"
